name: C/C++ Linter
on: [pull_request, push]
jobs:
  lint:
    runs-on: ubuntu-latest # Or other supported runners like macos-latest, windows-latest
    steps:
    - uses: actions/checkout@v5 # Checkout your repository code
    - name: Run C/C++ Linter
      uses: cpp-linter/cpp-linter-action@v2
      id: linter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for commenting/annotations
      with:
        style: 'file' # Use .clang-format config file in your repo
        tidy-checks: '' # Use .clang-tidy config file in your repo, or specify checks here
        # Other optional inputs can be added here, e.g.,
        # lines-changed-only: true
        # thread-comments: 'update'
    - name: Fail if linting checks failed
      if: steps.linter.outputs.checks-failed == 'true'
      run: |
        echo "C/C++ linting checks failed!"
        exit 1
    - name: install compilation tools
      run: |
        # sudo apt install clang
        wget -q https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi.tar.xz
        tar -xvf arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi.tar.xz
        python3 -m pip install --user pros-cli
    - name: Build
      run: |
        export PATH=$PATH:${GITHUB_WORKSPACE}/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi/bin/
        pros c add-depot LemLib https://raw.githubusercontent.com/LemLib/LemLib/depot/stable.json
        pros c apply LemLib
        make clean all
